adminUser:
  password: vault:jx-aps-plm8/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-plm8:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-plm8:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: PIPELINE_GITHUB_EMAIL
  token: vault:jx-aps-plm8/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: vault:jx-aps-plm8/prow:hmacToken
